# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run build!
      - run: npm run build

      - persist_to_workspace:
           root: ~/repo
           paths:
             - dist

  deploy:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - "4c:68:4e:d8:12:7a:d3:66:0e:3c:a6:68:98:df:a0:8a"
      - attach_workspace:
          at: /tmp/dist
      - run:
          name: run deploy
          environment:
            PROJECT_DIR: /var/www/todoapp
          command: |
            scp -o "StrictHostKeyChecking no" -r /tmp/dist/* ${SERVER_USERNAME}@${SERVER_ADDRESS}:${PROJECT_DIR}/ui/

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: release
